// BCaBA 6th Edition — 90 tasks across 9 domains
// Effective 2025 | Exported for import into App.jsx

export const BCABA_DOMAINS = [
  {
    key:"A", label:"Behaviorism & Philosophical Foundations",
    color:"#5A9E9E", q:10, pct:"7%",
    tasks:[
      { code:"A.1", title:"Goals of Behavior Analysis as a Natural Science",
        lesson:"Three goals: description (observing what behavior occurs), prediction (identifying correlated conditions), and control (demonstrating functional relationships through experimental manipulation).",
        why:"Goals justify ABA's experimental methodology and distinguish it from opinion-based approaches.",
        examples:["Description: ABC data, frequency recording, baseline measurement","Prediction: recognizing reliable antecedent-behavior relationships","Control: experimental functional analysis, single-case design phases","Goals build: describe→predict→control"],
        tip:"In ABA, the goal of control is achieved through single-case experimental designs.",
        mc:{q:"A BCaBA demonstrates behavior changes only when intervention is in effect using reversal design. This primarily demonstrates:",opts:["Description","Prediction","Control","Generalization"],a:2,ex:"Demonstrating a functional relationship — behavior changes with IV and reverses without it — is the goal of control."},
        sc:{q:"A BCaBA graphs baseline data and notices self-injury is reliably higher in the morning. This represents:",opts:["Control","Description","Prediction","Measurement"],a:2,ex:"Identifying conditions reliably correlated with behavior is prediction — not yet control."},
        fl:{f:"What are the 3 goals of behavior analysis as a natural science?",b:"1. Description → systematic observation of behavior\n2. Prediction → conditions reliably associated\n3. Control → IV causes DV change\n\nSequential: description→prediction→control"}
      },
      { code:"A.2", title:"Philosophical Assumptions of Behavior Analysis",
        lesson:"Five assumptions: selectionism (consequences shape behavior), determinism (lawful causes), empiricism (knowledge from observation), parsimony (simplest explanation), pragmatism (truth by effectiveness).",
        why:"Assumptions define how BCaBAs explain behavior — always seeking environmental causes, relying on direct data.",
        examples:["Selectionism: behavior maintained by consequences parallels natural selection","Determinism: seek environmental causes","Empiricism: data over clinical intuition","Parsimony: avoid hypothetical constructs","Pragmatism: evidence-based = practically true"],
        tip:"Parsimony is most commonly tested — select the simplest, most directly testable explanation.",
        mc:{q:"BCaBA prefers a reinforcement-based explanation over a neurological hypothesis when data supports both. This reflects:",opts:["Pragmatism","Empiricism","Parsimony","Selectionism"],a:2,ex:"Parsimony: simplest explanation requiring fewest assumptions."},
        sc:{q:"BCaBA relies on direct observation rather than parent report to assess behavior frequency. This reflects:",opts:["Selectionism","Parsimony","Empiricism","Determinism"],a:2,ex:"Empiricism: knowledge from direct, systematic observation."},
        fl:{f:"Define all 5 philosophical assumptions.",b:"Selectionism: behavior shaped by consequences\nDeterminism: behavior has lawful causes\nEmpiricism: knowledge from direct observation\nParsimony: prefer simplest explanation\nPragmatism: truth judged by effectiveness"}
      },
      { code:"A.3", title:"Radical Behaviorism",
        lesson:"Includes private events as behavior subject to behavioral principles — not as causes. Rejects mentalism while acknowledging private events exist.",
        why:"Distinguishes ABA from cognitive approaches — BCaBAs conduct functional analyses rather than inferring internal causes.",
        examples:["Private events are behaviors, not causes","'Feeling anxious' is verbal behavior, not a cause of avoidance","Methodological: excludes private events entirely","Radical: includes them as behavior in their own right"],
        tip:"Ask: what environmental variables produce that behavior? Not: what internal state caused it?",
        mc:{q:"Radical behaviorism differs from methodological behaviorism in that it:",opts:["Excludes private events","Explains behavior using cognitive constructs","Includes private events as behavior subject to behavioral principles","Focuses only on observable behavior"],a:2,ex:"Radical acknowledges private events as real behaviors — subject to same analysis as public behavior."},
        sc:{q:"Colleague says: 'He's aggressive because he has low frustration tolerance.' A radical behaviorist would critique this as:",opts:["A useful clinical hypothesis","Mentalism — hypothetical internal state without functional analysis","Appropriate behavioral explanation","Valid assessment-based inference"],a:1,ex:"Attributing behavior to 'frustration tolerance' is mentalism — circular, non-testable."},
        fl:{f:"What is mentalism and why does radical behaviorism reject it?",b:"Mentalism: explaining behavior by hypothetical internal states\n\nRejected because:\n• Can't be directly observed or manipulated\n• Don't identify changeable variables\n• Create circular explanations\n• Divert from functional analysis"}
      },
      { code:"A.4", title:"Behaviorism, EAB, ABA & Professional Practice",
        lesson:"Behaviorism = philosophy. EAB = basic science in controlled settings. ABA = applied science with socially significant behavior. Professional practice = credentialed service delivery.",
        why:"BCaBAs must understand where their work sits in this hierarchy.",
        examples:["Behaviorism: Skinner's philosophical writings","EAB: lab reinforcement schedule research with animals","ABA: using reinforcement to teach communication","Professional practice: BCaBA implementing programs under BCBA supervision"],
        tip:"EAB provides basic principles; ABA applies them; professional practice delivers applications ethically.",
        mc:{q:"A researcher studies basic reinforcement principles using rats in a Skinner box. This is:",opts:["ABA","Behaviorism","EAB","Professional practice"],a:2,ex:"EAB is basic science — controlled laboratory settings, non-human subjects, fundamental principles."},
        sc:{q:"A BCaBA uses JABA research on FCT to develop a client's behavior plan. She is:",opts:["Conducting EAB research","Applying basic science through ABA in professional practice","Conducting behavioral philosophy","Violating scope of practice"],a:1,ex:"Using peer-reviewed ABA research to inform clinical intervention bridges EAB/ABA and professional practice."},
        fl:{f:"Relationship between EAB, ABA, and professional practice?",b:"EAB → identifies fundamental principles (lab)\n↓\nABA → applies to socially significant behavior\n↓\nProfessional practice → credentialed delivery\n\nEach level builds on the level above"}
      },
      { code:"A.5", title:"Dimensions of Applied Behavior Analysis",
        lesson:"Baer, Wolf & Risley (1968) defined 7 dimensions: Applied, Behavioral, Analytic, Technological, Conceptually Systematic, Effective, and Generality.",
        why:"Define what makes a practice genuinely ABA. BCaBAs must ensure all 7 are present.",
        examples:["Applied: socially significant behavior","Behavioral: objective, measurable","Analytic: experimental control","Technological: replicable procedures","Conceptually systematic: derived from principles","Effective: meaningful change","Generality: persists across time and settings"],
        tip:"Use the 7 dimensions as a quality checklist — missing even one means not fully ABA.",
        mc:{q:"BCaBA writes procedures so detailed any trained clinician could implement them identically. This satisfies:",opts:["Analytic","Applied","Technological","Effective"],a:2,ex:"Technological: procedures described with sufficient specificity for replication."},
        sc:{q:"Behavior changes in clinic but not at home or school. Which dimension is not fully met?",opts:["Effective","Analytic","Behavioral","Generality"],a:3,ex:"Generality requires change to persist across relevant environments."},
        fl:{f:"Name all 7 dimensions of ABA.",b:"A — Applied: socially significant behavior\nB — Behavioral: observable and measurable\nA — Analytic: experimental control\nT — Technological: replicable by others\nA — Conceptually Systematic: derived from principles\nE — Effective: meaningful change\nG — Generality: persists across time and contexts"}
      },
    ]
  },
  {
    key:"B", label:"Concepts & Principles",
    color:"#7B5EA7", q:18, pct:"12%",
    tasks:[
      { code:"B.3", title:"Respondent & Operant Conditioning",
        lesson:"Respondent: stimulus-stimulus pairing creates CS eliciting conditioned response. Operant: response-consequence contingency selects behavior through three-term contingency (SD→R→SR).",
        why:"Both processes always operate. BCaBAs must identify which process is relevant and design accordingly.",
        examples:["Respondent: therapy room + aversive → therapy room becomes CS eliciting fear","Operant: task refusal → escape → refusal increases","Pairing tokens with backup reinforcers uses respondent conditioning"],
        tip:"Phobias and conditioned emotional responses are respondent; most challenging behaviors are operant.",
        mc:{q:"Client develops fear of therapy room after a painful procedure there. Acquired through:",opts:["Operant conditioning","Respondent conditioning — NS paired with aversive US","Negative reinforcement","Automatic punishment"],a:1,ex:"Through respondent conditioning (pairing), neutral therapy room became CS eliciting conditioned fear."},
        sc:{q:"Aggression increases when demands are present and decreases when removed. Maintained by:",opts:["Respondent conditioning","Operant conditioning — negative reinforcement","Automatic reinforcement","Classical conditioning"],a:1,ex:"Aggression (operant) is negatively reinforced by escape from demands."},
        fl:{f:"Respondent vs. Operant — key distinctions",b:"Respondent:\n• Stimulus-stimulus pairing\n• Behavior ELICITED\n• Reflexive/involuntary\n\nOperant:\n• Response-consequence contingency\n• Behavior EMITTED\n• Voluntary, maintained by reinforcement\n\nBoth operate simultaneously"}
      },
      { code:"B.4", title:"Positive & Negative Reinforcement",
        lesson:"Positive SR: add stimulus → behavior increases. Negative SR: remove stimulus → behavior increases. Both INCREASE behavior — defined by effect, not intent.",
        why:"Misidentifying reinforcement type leads to wrong function-based treatment.",
        examples:["Positive SR: token after correct response → increases","Negative SR: demand removed after FCT → FCT use increases","Inadvertent negative SR: removing work after tantrum","NCR for escape: scheduled breaks abolish EO"],
        tip:"Negative reinforcement = removal + increase. Both words required.",
        mc:{q:"Student completes assignments when doing so results in being excused from remaining work. This is:",opts:["Positive reinforcement","Negative reinforcement","Automatic reinforcement","Negative punishment"],a:1,ex:"Completing assignments removes remaining work → behavior increases = negative reinforcement."},
        sc:{q:"NCR addresses escape-maintained behavior by providing scheduled breaks. The mechanism is:",opts:["Punishing behavior","Abolishing EO — breaks freely available so behavior not needed","Reinforcing incompatible behavior","Establishing new SD"],a:1,ex:"NCR abolishes the EO — when escape is freely available, motivation to engage in problem behavior is eliminated."},
        fl:{f:"Critical rule for positive vs. negative reinforcement",b:"Positive SR+: ADD → INCREASES\nNegative SR-: REMOVE → INCREASES\n\nBoth = REINFORCEMENT = INCREASES\n+/- = what happened to the environment, not good/bad\n\nDefined by EFFECT — not intention"}
      },
      { code:"B.7", title:"Unconditioned, Conditioned & Generalized Reinforcers",
        lesson:"Unconditioned: biological value without learning (food, water). Conditioned: value through pairing (praise, tokens). Generalized conditioned: paired with many reinforcers, effective across diverse MOs (money, points).",
        why:"Understanding reinforcer types guides selection and maintenance of reinforcement tools.",
        examples:["Unconditioned SR: food, water, warmth","Conditioned SR: tokens, praise","Generalized conditioned SR: money, grades","Token values deteriorate without continued pairing"],
        tip:"Generalized conditioned reinforcers are robust — don't depend on any single MO.",
        mc:{q:"Money is effective as a reinforcer across many different conditions. This makes it a:",opts:["Unconditioned reinforcer","Conditioned reinforcer","Generalized conditioned reinforcer","Motivating operation"],a:2,ex:"Money has been paired with so many reinforcers that it maintains value across diverse MOs."},
        sc:{q:"Tokens in a token economy initially have no effect. To establish them:",opts:["Give freely first","Pair consistently and immediately with valued backup reinforcers","Use as punishers first","Deliver on VR schedule immediately"],a:1,ex:"Tokens become conditioned reinforcers through repeated, consistent pairing with backup reinforcers."},
        fl:{f:"Unconditioned vs. Conditioned vs. Generalized Conditioned Reinforcers",b:"Unconditioned: biological value without learning\n\nConditioned: value through pairing\n→ Fluctuates with MOs; requires continued pairing\n\nGeneralized conditioned: paired with MANY reinforcers\n→ Effective across diverse MOs; most stable"}
      },
      { code:"B.12", title:"Motivating Operations",
        lesson:"MOs alter both the reinforcing effectiveness of a stimulus AND the frequency of behavior that produces it. EOs increase effectiveness; AOs decrease it.",
        why:"MOs explain variability in session performance — essential for understanding 'off days.'",
        examples:["EO: food deprivation → food more reinforcing + food-seeking increases","AO: satiation → food less reinforcing + food-seeking decreases","Both effects simultaneous: value-altering AND behavior-altering"],
        tip:"Always assess current MOs before a session — same reinforcer may not be equally effective.",
        mc:{q:"Child who just finished lunch shows reduced responding for food reinforcers. This reflects:",opts:["An establishing operation","Behavioral contrast","An abolishing operation","Extinction"],a:2,ex:"Satiation (abolishing operation) decreases food reinforcer value."},
        sc:{q:"BCaBA checks with parent before sessions to ask if client ate recently. Clinical purpose:",opts:["Build rapport","Assess potential MOs affecting reinforcer effectiveness","Determine session duration","Plan data collection"],a:1,ex:"Recent eating affects food deprivation (MO) and effectiveness of food reinforcers."},
        fl:{f:"2 effects of every motivating operation?",b:"1. Value-altering: changes reinforcer effectiveness\n   EO: INCREASES; AO: DECREASES\n\n2. Behavior-altering: changes frequency of related behavior\n   EO: INCREASES behavior\n   AO: DECREASES behavior"}
      },
      { code:"B.14", title:"Elementary Verbal Operants",
        lesson:"Six verbal operants: mand (MO→request→specific SR), tact (nonverbal→label→generalized SR), echoic, intraverbal, textual, transcription.",
        why:"Verbal behavior analysis allows BCaBAs to design targeted language programs.",
        examples:["Mand: 'cookie please' → gets cookie","Tact: sees dog → 'dog'","Echoic: adult says 'ball' → child says 'ball'","Intraverbal: 'What do you eat with?' → 'A fork'"],
        tip:"Mand training is highest priority — only operant directly reinforced by what the speaker gets.",
        mc:{q:"Child says 'juice' when thirsty and receives juice. This verbal operant is a:",opts:["Tact","Intraverbal","Mand","Echoic"],a:2,ex:"Mand: occasioned by MO (thirst), reinforced by specific item requested (juice)."},
        sc:{q:"Client is asked 'What color is the sky?' and responds 'blue.' No object present. This is a(n):",opts:["Tact","Mand","Intraverbal","Echoic"],a:2,ex:"Verbal response to verbal antecedent, no nonverbal stimulus, generalized social SR = intraverbal."},
        fl:{f:"Define the 6 verbal operants by antecedent and reinforcer.",b:"Mand: MO → request → SPECIFIC reinforcer\nTact: nonverbal stimulus → label → generalized SR+\nEchoic: verbal → point-to-point repeat → generalized SR+\nIntraverbal: verbal → different verbal → generalized SR+\nTextual: written text → vocal → generalized SR+\nTranscription: verbal → written → generalized SR+"}
      },
    ]
  },
  {
    key:"C", label:"Measurement, Data Display & Interpretation",
    color:"#5A9E9E", q:20, pct:"13%",
    tasks:[
      { code:"C.2", title:"Topography & Operational Definitions",
        lesson:"Topography describes the physical form of behavior. Operational definitions specify behavior in observable, measurable, and unambiguous terms.",
        why:"Without precise operational definitions, data is unreliable — the whole treatment depends on definition quality.",
        examples:["Poor: 'aggressive behavior'","Better: 'forceful contact with another person's body using hand/foot/head'","Includes both topography and parameters","Stranger test: could a stranger use this reliably?"],
        tip:"Define what COUNTS and what DOESN'T count — boundary cases are where definitions fail.",
        mc:{q:"Which definition best meets criteria for a good operational definition of 'elopement'?",opts:["Client leaves the therapy area","Client moves more than 5 feet from designated therapy space without adult permission","Client is hard to supervise","Client doesn't follow directions"],a:1,ex:"Observable, measurable, unambiguous — '5 feet without permission' provides clear, quantifiable parameters."},
        sc:{q:"Two therapists record very different frequencies for the same behavior. Most likely cause:",opts:["Different experience levels","Unclear or non-operational behavior definition","Different data collection methods","Client behavior variability"],a:1,ex:"Low IOA typically indicates behavior definition is not precise enough for consistent recording."},
        fl:{f:"3 criteria a good operational definition must meet?",b:"1. Observable — can be directly seen or heard\n2. Measurable — can be counted, timed, quantified\n3. Unambiguous — any trained observer records same event\n\nStranger test: could someone unfamiliar use this reliably?"}
      },
      { code:"C.4", title:"Continuous Measurement Procedures",
        lesson:"Continuous measurement records every instance: event recording, rate recording, duration, latency, and IRT.",
        why:"Provides the most complete, accurate data — used when every instance matters.",
        examples:["Event recording: tally mark per response","Duration: stopwatch during each instance","Latency: timer from SD to first response","Rate: events ÷ observation time"],
        tip:"Continuous measurement is ideal when accuracy is paramount — impractical for very high-rate behaviors.",
        mc:{q:"BCaBA records the exact time each tantrum begins and ends throughout a session. This is:",opts:["Event recording","Frequency recording","Duration recording","Permanent product"],a:2,ex:"Recording start and end times to capture how long each instance lasts = duration recording."},
        sc:{q:"A behavior occurs so rapidly it cannot be counted individually. BCaBA should consider:",opts:["Continuous event recording","Duration per instance","Discontinuous measurement","Permanent product"],a:2,ex:"When behavior rate is too high for continuous recording, discontinuous methods provide manageable estimates."},
        fl:{f:"4 types of continuous measurement?",b:"Event/Frequency: discrete, countable — when count matters\nRate: frequency ÷ time — when comparing across sessions\nDuration: when length of behavior is relevant\nLatency: when response speed matters\nIRT: when inter-response timing is the focus"}
      },
      { code:"C.9", title:"Interpret Graphed Data",
        lesson:"Visual analysis examines level (mean value), trend (slope direction), and variability (spread) — within phases and across phases.",
        why:"BCaBAs make clinical decisions based on graphed data — accurate visual analysis determines when to continue, modify, or change interventions.",
        examples:["Level: average value in a phase","Trend: accelerating, decelerating, or stable","Variability: spread of data points","Across phases: compare all three features","Low overlap = strong intervention effect"],
        tip:"Analyze within each phase first, then compare across phases.",
        mc:{q:"Comparing stable high-level baseline to stable low-level intervention represents a change in:",opts:["Trend only","Variability only","Level — mean value shifted across phases","Overlap"],a:2,ex:"Stable data shifting to new value without slope change = change in level."},
        sc:{q:"Behavior decreases during intervention but with high variability. BCaBA should:",opts:["Discontinue","Celebrate any decrease","Investigate environmental variables causing inconsistency","Implement extinction immediately"],a:2,ex:"High variability suggests environmental inconsistency — investigation needed."},
        fl:{f:"3 features analyzed in visual analysis?",b:"1. Level — average value within a phase\n2. Trend — direction (increasing, decreasing, flat)\n3. Variability — spread/consistency\n\nWithin phases → then across phases\n\nStrong effect: change in level or trend + low overlap"}
      },
    ]
  },
  {
    key:"D", label:"Experimental Design",
    color:"#E8845A", q:10, pct:"7%",
    tasks:[
      { code:"D.3", title:"Single-Case Experimental Design Features",
        lesson:"Individual serves as own control, repeated measurement, experimental control through prediction, verification, and replication.",
        why:"Primary research methodology in ABA — allows experimental analysis without requiring large groups.",
        examples:["Individual as own control: compare phases within same person","Repeated measurement: many data points","Prediction: baseline projects future without intervention","Verification: effect shown when conditions change","Replication: effect demonstrated more than once"],
        tip:"PVR — Prediction, Verification, Replication — all three must be present for strong experimental control.",
        mc:{q:"In single-case design, 'verification' refers to:",opts:["Checking IOA","Confirming operational definition","Demonstrating behavior changes when conditions change and returns when reverted","Publishing results"],a:2,ex:"Verification confirms the experimental effect — behavior changes with IV introduction and reverses with withdrawal."},
        sc:{q:"BCaBA collects 5 stable baseline points before introducing intervention. Purpose:",opts:["Establish prediction — what behavior would continue without intervention","Establish treatment fidelity","Increase IOA","Identify correct reinforcer"],a:0,ex:"Stable baseline establishes prediction — how behavior will continue without intervention."},
        fl:{f:"3 elements that establish experimental control in single-case designs?",b:"1. Prediction: stable baseline projects future behavior\n2. Verification: introducing/removing IV confirms behavior changes\n3. Replication: effect demonstrated more than once\n\nAll 3 = strong internal validity (PVR)"}
      },
      { code:"D.5", title:"Single-Case Experimental Designs",
        lesson:"Reversal (ABAB): demonstrate functional relationship by withdrawing and reintroducing IV. Multiple baseline: stagger introduction across tiers. Multielement: rapidly alternate conditions. Changing criterion: criterion changes systematically.",
        why:"Each design serves different purposes. BCaBAs select based on behavior, ethics, and clinical context.",
        examples:["Reversal: powerful but requires behavior to reverse","Multiple baseline: ethical when reversal inappropriate","Multielement: compare 2+ interventions","Changing criterion: evaluate shaping/chaining"],
        tip:"When reversal is unethical, multiple baseline is the design of choice.",
        mc:{q:"Which design is BEST when withdrawing treatment could be harmful?",opts:["ABAB reversal","Multielement","Changing criterion","Multiple baseline"],a:3,ex:"Multiple baseline demonstrates control without requiring treatment withdrawal."},
        sc:{q:"BCaBA wants to compare two prompting procedures for the same client. Most appropriate design:",opts:["Reversal","Multiple baseline across behaviors","Multielement (alternating treatments)","Changing criterion"],a:2,ex:"Multielement rapidly alternates between conditions to compare effects directly."},
        fl:{f:"What is each single-case design used for?",b:"Reversal (ABAB): functional relationship by withdrawing/reintroducing IV\nMultiple Baseline: control without reversal — stagger across tiers\nMultielement/ATD: compare 2+ conditions rapidly\nChanging Criterion: evaluate shaping/chaining — criterion changes stepwise"}
      },
    ]
  },
  {
    key:"E", label:"Ethical & Professional Issues",
    color:"#D4607A", q:18, pct:"12%",
    tasks:[
      { code:"E.1", title:"Core Principles of the Ethics Code",
        lesson:"Core principles: benefit others; treat others with compassion, dignity, and respect; behave with integrity.",
        why:"Core principles guide decisions in situations not explicitly addressed by specific standards.",
        examples:["Benefit others: prioritize client welfare above convenience","Dignity and respect: in all interactions","Integrity: honest in all professional communications","Apply when specific guidance is absent"],
        tip:"When facing an ethical dilemma not explicitly covered: will this benefit the client, treat everyone with dignity, and reflect integrity?",
        mc:{q:"The BACB Ethics Code's core principles are best described as:",opts:["Specific rules to follow","Philosophical foundations guiding behavior when specific rules don't apply","Optional guidelines for experienced practitioners","Primarily relevant to BCBAs only"],a:1,ex:"Core principles are philosophical foundations — they guide ethical reasoning in ambiguous situations."},
        sc:{q:"BCaBA faces an ethical situation not addressed by specific code standard. She should:",opts:["Ask supervisor to handle it","Proceed as most convenient","Apply core principles — benefit others, respect dignity, behave with integrity","Wait for a code update"],a:2,ex:"When specific guidance is absent, core principles guide ethical decision-making."},
        fl:{f:"3 core principles of the BACB Ethics Code?",b:"1. Benefit others — prioritize client and stakeholder welfare\n2. Treat others with compassion, dignity, and respect\n3. Behave with integrity — honest and ethical in all activities"}
      },
      { code:"E.5", title:"Confidentiality Requirements",
        lesson:"BCaBAs must collect, use, protect, and disclose client information in accordance with HIPAA and applicable regulations.",
        why:"Client privacy is a legal and ethical right — violations cause real harm and serious professional consequences.",
        examples:["Secure storage of session data","Share only with authorized parties","Telehealth: HIPAA-compliant platforms only","Social media: no client info, even without names"],
        tip:"The question is not just 'is this harmful?' but 'is this authorized?'",
        mc:{q:"Parent asks BCaBA to share child's behavior plan with private tutor. BCaBA should:",opts:["Share immediately — parent authorized","Obtain signed release and follow organizational procedures first","Refuse — plans cannot be shared","Email it directly"],a:1,ex:"Even with parent authorization, proper channels must be followed."},
        sc:{q:"BCaBA discusses a client case with colleague at a coffee shop, using first name only. This:",opts:["Is acceptable — no last name used","May still be a confidentiality violation if client could be identified","Is completely private in public","Is acceptable professional consultation"],a:1,ex:"Any information that could identify a client — including first name with other details — can constitute a violation."},
        fl:{f:"4 activities involving client information requiring compliance?",b:"1. Collecting — only what's necessary\n2. Using — only for authorized clinical purposes\n3. Protecting — secure storage, no public discussion\n4. Disclosing — only with proper authorization"}
      },
      { code:"E.9", title:"Cultural Humility",
        lesson:"Ongoing self-reflection about personal biases and genuine responsiveness to each client's cultural context — not claiming cultural mastery.",
        why:"Cultural factors profoundly affect behavior, reinforcement, family priorities, and treatment acceptability.",
        examples:["Examine cultural assumptions before clinical decisions","Ask families about their values","Adapt reinforcers and goals to cultural context","Continuous practice, not a credential"],
        tip:"Cultural humility is different from cultural competence — continuous learning and self-reflection, not mastery.",
        mc:{q:"Cultural humility differs from cultural competence primarily because it:",opts:["Focuses on learning specific cultures","Requires formal multicultural training","Involves ongoing self-reflection rather than claiming mastery","Is only relevant for international clients"],a:2,ex:"Cultural humility centers ongoing self-reflection and responsive engagement — there's no finish line."},
        sc:{q:"BCaBA assumes family practices are problematic because they differ from mainstream norms. This reflects failure of:",opts:["Evidence-based practice","Supervision competence","Cultural humility — personal biases affecting clinical judgment","Documentation standards"],a:2,ex:"Judging family practices without reflection = cultural bias, not humility."},
        fl:{f:"Cultural humility vs. cultural competence?",b:"Cultural competence: implies mastery\n\nCultural humility:\n• Ongoing self-reflection about biases\n• Recognizing limits of knowledge\n• Centering client/family as expert on own culture\n• Continuous learning\n\nNo finish line"}
      },
    ]
  },
  {
    key:"F", label:"Behavior Assessment",
    color:"#E8B84B", q:17, pct:"11%",
    tasks:[
      { code:"F.4", title:"Assess Skill Strengths & Deficits",
        lesson:"BCaBAs implement assessments of relevant skill strengths, areas of need, and contextual fit — including client values, cultural variables, social validity, and environmental resources.",
        why:"Comprehensive skill assessment identifies what to teach, what to build on, and whether context supports intervention.",
        examples:["VB-MAPP, ABLLS-R, AFLS, PEAK tools","Domain coverage: language, social, self-care, academic, motor","Contextual fit: can family implement this program?","Social validity: does this skill matter to client's life?"],
        tip:"Always start with what the client CAN do — strengths provide the foundation.",
        mc:{q:"Contextual fit in skill assessment refers to:",opts:["Whether assessment was conducted correctly","Whether planned intervention is feasible given client's environment, culture, and resources","Whether assessment tools are standardized","Whether client was cooperative"],a:1,ex:"Contextual fit assesses whether intervention can realistically be implemented — family capacity, cultural alignment, resources."},
        sc:{q:"BCaBA completes a VB-MAPP and identifies communication targets. Before finalizing the program she should also assess:",opts:["Client's classroom placement","Contextual fit — whether family can implement targets at home","Whether diagnosis is accurate","Whether assessment norms apply"],a:1,ex:"Assessment-to-programming requires checking contextual fit — family ability and resources to support targets."},
        fl:{f:"What does comprehensive skill assessment include beyond standardized scores?",b:"• Skill strengths (what client already does)\n• Areas of need\n• Contextual fit (family resources, environment)\n• Cultural variables\n• Social validity (does this skill matter?)\n• Environmental resources available"}
      },
      { code:"F.5", title:"Preference & Reinforcer Assessments",
        lesson:"Preference assessments identify what clients prefer. Reinforcer assessments verify that preferred items actually function as reinforcers.",
        why:"Preference does not equal reinforcement — systematic assessment prevents ineffective reinforcers.",
        examples:["Free operant: natural approach behavior","Paired stimulus, MSWO: structured preference hierarchy","Reinforcer assessment: verify preferences INCREASE target behavior"],
        tip:"Always verify — preference tells you what client wants; only data tells you what functions as reinforcement.",
        mc:{q:"What distinguishes a reinforcer assessment from a preference assessment?",opts:["Uses more items","Verifies that a preferred item actually increases behavior","Is more structured","They are the same procedure"],a:1,ex:"Preference = what client likes. Reinforcer assessment = verifies preferred items functionally increase behavior."},
        sc:{q:"Client consistently chooses bubbles but task completion doesn't increase when bubbles are used. You should:",opts:["Continue using bubbles — preference is best guide","Identify other preferred items and run reinforcer assessments","Assume task is too hard","Run more preference assessments"],a:1,ex:"Bubbles are preferred but not functioning as reinforcer. Identify other items and verify reinforcing function."},
        fl:{f:"Preference assessment vs. Reinforcer assessment?",b:"Preference assessment: identifies what client approaches/chooses\n→ Tells you WHAT THEY LIKE\n\nReinforcer assessment: verifies preferred items INCREASE target behavior\n→ Tells you WHAT WORKS\n\nPreference ≠ reinforcement. Always verify."}
      },
      { code:"F.6", title:"Functional Assessments",
        lesson:"Three levels: indirect (interviews, rating scales), descriptive (direct observation, ABC data), and experimental functional analysis — each with increasing confidence in functional conclusions.",
        why:"Treatment matched to behavioral function is dramatically more effective.",
        examples:["Indirect: MAS, QABF, structured interview","Descriptive: ABC data, scatter plot","Functional analysis: attention, escape, alone, play/control conditions","Progression: indirect→descriptive→experimental"],
        tip:"Progression from indirect→descriptive→experimental represents increasing confidence. Use the level appropriate to clinical need.",
        mc:{q:"Which level of functional assessment provides STRONGEST evidence for behavioral function?",opts:["Parent interview","Rating scales (QABF, MAS)","ABC data collection","Experimental functional analysis"],a:3,ex:"Experimental FA manipulates variables in controlled conditions to demonstrate a functional relationship."},
        sc:{q:"BCaBA's ABC data suggests escape function, but behavior is severe. Before developing a plan:",opts:["Develop plan based on ABC data alone","Conduct experimental FA to verify function","Ask staff for opinion","Implement multi-function plan"],a:1,ex:"For severe behavior, verifying function through experimental FA ensures treatment targets the correct function."},
        fl:{f:"3 levels of functional assessment?",b:"1. Indirect — interviews, rating scales\n→ Fastest; most subject to bias\n\n2. Descriptive — ABC, scatter plots, observation\n→ Direct but correlational\n\n3. Experimental FA — controlled manipulation\n→ Strongest evidence; establishes functional relationship"}
      },
    ]
  },
  {
    key:"G", label:"Behavior-Change Procedures",
    color:"#7B5EA7", q:22, pct:"15%",
    tasks:[
      { code:"G.1", title:"Positive & Negative Reinforcement Procedures",
        lesson:"BCaBAs develop both contingent and noncontingent applications. NCR delivers reinforcement on a time schedule independent of behavior — abolishing the EO for problem behavior.",
        why:"Both have distinct clinical applications. NCR is a powerful antecedent intervention.",
        examples:["Contingent SR+: token after correct response","NCR: attention every 3 minutes regardless of behavior","NCR mechanism: abolishes the EO"],
        tip:"NCR abolishes the EO — makes the reinforcer available so problem behavior is no longer necessary.",
        mc:{q:"BCaBA delivers preferred items on a fixed-time schedule regardless of behavior. This is:",opts:["Contingent reinforcement","Variable ratio schedule","NCR — noncontingent reinforcement","FR1 schedule"],a:2,ex:"NCR delivers reinforcement on a time schedule without requiring any specific behavior."},
        sc:{q:"NCR reduces problem behavior by:",opts:["Punishing behavior","Reinforcing incompatible behavior","Abolishing EO — reinforcer freely available so behavior unnecessary","Providing extinction"],a:2,ex:"NCR abolishes the establishing operation — behavior becomes unnecessary to access the reinforcer."},
        fl:{f:"Contingent vs. Noncontingent Reinforcement?",b:"Contingent SR: delivered AFTER specific behavior → increases that behavior\n\nNCR: delivered on time schedule regardless of behavior\n\nNCR: abolish EO for problem behavior\n→ Most effective for attention-maintained and tangible-maintained"}
      },
      { code:"G.5", title:"Prompting Procedures with Fading",
        lesson:"BCaBAs develop procedures using stimulus and response prompts — including errorless, LTM, MTL, and time delay — with systematic fading to transfer control to natural SDs.",
        why:"Prompts are temporary scaffolds. Without planned fading, prompt dependency prevents independence.",
        examples:["Stimulus prompts: position, redundancy, stimulus shape","Response prompts: physical, model, verbal, gestural","Errorless: prompt before any error","Time delay: pause before prompting"],
        tip:"Plan fading BEFORE starting — prompt dependency happens when fading is neglected.",
        mc:{q:"BCaBA inserts a 4-second pause between SD and prompt to allow independent responding. This is:",opts:["Errorless teaching","Least-to-most","Time delay","Graduated guidance"],a:2,ex:"Time delay inserts a systematic pause between SD and prompt — creating opportunity for independent responding."},
        sc:{q:"Client consistently needs full physical prompt for a motor skill. To fade:",opts:["MTL with graduated guidance — systematically reduce physical support","Remove all prompts immediately","Switch to verbal prompting only","Increase number of trials"],a:0,ex:"MTL with graduated guidance systematically reduces physical support from full to partial to shadowing."},
        fl:{f:"5 response prompt types from most to least intrusive?",b:"1. Full physical (hand-over-hand)\n2. Partial physical (light touch)\n3. Model (demonstrate)\n4. Verbal (instruction)\n5. Gestural (point, nod)\n\nPlan fading BEFORE beginning."}
      },
      { code:"G.18", title:"Differential Reinforcement with & without Extinction",
        lesson:"DR procedures (DRO, DRA, DRI, DRL) can be implemented with or without extinction. Adding extinction significantly increases effectiveness.",
        why:"Without extinction, problem behavior may persist alongside the alternative.",
        examples:["DRA + extinction: reinforce alternative AND stop reinforcing problem","DRA without extinction: alternative reinforced but problem still sometimes gets SR","Extinction burst expected when adding extinction"],
        tip:"DR without extinction is less effective but may be necessary when extinction is clinically contraindicated.",
        mc:{q:"DRA + extinction is more effective than DRA alone because:",opts:["Extinction provides punishment","Alternative reinforced more frequently","Problem behavior no longer reinforced — alternative is only path","Extinction reduces bursts"],a:2,ex:"Adding extinction ensures problem behavior no longer produces reinforcement."},
        sc:{q:"BCaBA implements DRI for hitting (hands-flat earns SR). Hitting rate doesn't decrease much. Most likely reason:",opts:["DRI is wrong procedure","Extinction wasn't added — hitting may still be reinforced","Reinforcer isn't strong enough","DRI behavior is too easy"],a:1,ex:"DRI alone without extinction allows hitting to still occasionally produce reinforcement."},
        fl:{f:"Why is extinction important when implementing DR procedures?",b:"Without extinction:\nProblem behavior AND alternative both sometimes produce SR → competition\n\nWith extinction:\nOnly alternative produces SR → problem behavior no longer effective\n\nResult: DR + extinction significantly more effective than DR alone"}
      },
    ]
  },
  {
    key:"H", label:"Intervention Development & Monitoring",
    color:"#E8845A", q:20, pct:"13%",
    tasks:[
      { code:"H.1", title:"State Goals in Observable & Measurable Terms",
        lesson:"Intervention goals must be stated in observable, measurable terms so that progress can be objectively assessed by any trained observer.",
        why:"Vague goals cannot be measured. Unmeasured goals cannot be evaluated or improved.",
        examples:["Vague: 'improve communication skills'","Measurable: 'will independently request preferred items using 3+ word phrases in 4/5 opportunities across 3 sessions'","Components: behavior, condition, criterion, consistency"],
        tip:"Write goals in terms of what you would see and count — not what you hope the client feels.",
        mc:{q:"Which goal statement is MOST observable and measurable?",opts:["Client will improve social skills","Client will show better behavior at school","Client will greet peers with wave or verbal greeting in 4/5 opportunities across 3 school days","Client will want to interact with peers more"],a:2,ex:"Observable (wave or verbal), measurable (4/5 opportunities), specified (3 days) — all criteria met."},
        sc:{q:"Goal states 'client will understand money concepts.' BCaBA should revise to:",opts:["Keep it — clear enough","Client will identify coins by name in 4/5 trials","Client will demonstrate knowledge of money","Client will handle money appropriately"],a:1,ex:"'Identify coins by name in 4/5 trials' is observable and measurable. 'Understand' cannot be observed."},
        fl:{f:"4 components of a well-written behavioral goal?",b:"1. Behavior — observable, measurable description\n2. Condition — context/antecedent\n3. Criterion — level of performance required\n4. Consistency — sessions/observations required\n\nTest: can you measure progress RIGHT NOW?"}
      },
      { code:"H.6", title:"Evaluate Client Progress & Procedural Integrity",
        lesson:"BCaBAs evaluate both client progress (are goals being achieved?) and procedural integrity (is intervention being implemented as designed?).",
        why:"Poor outcomes might reflect ineffective procedures OR poor implementation — BCaBAs must distinguish between them.",
        examples:["Client progress: graph review, mastery criteria","Procedural integrity: observation checklists, treatment fidelity forms","Low progress + high fidelity: program needs modification","Low progress + low fidelity: training is the problem"],
        tip:"Always check procedural integrity before concluding a program isn't working.",
        mc:{q:"BCaBA finds a client is not meeting progress targets. The FIRST thing to assess is:",opts:["Whether goal is too difficult","Whether program is implemented with high fidelity","Whether client is motivated","Whether new assessment is needed"],a:1,ex:"Low progress could be program failure OR implementation failure. Check fidelity first."},
        sc:{q:"Procedural integrity data shows RBT has been omitting error correction step. This explains why:",opts:["Client has been acquiring skills correctly","Progress has been slow — program hasn't been fully implemented","Data should be discarded","Program should be simplified"],a:1,ex:"Omitting error correction changes the contingencies — progress problems attributed to implementation failure."},
        fl:{f:"How does procedural integrity guide clinical decisions?",b:"Low integrity + low progress → fix implementation first\nHigh integrity + low progress → modify program design\n\nAssessed by:\n• Direct observation with implementation checklist\n• Scoring each step as implemented\n• Calculating % steps correctly implemented"}
      },
    ]
  },
  {
    key:"I", label:"Supervisory Relationships",
    color:"#1a3a5c", q:15, pct:"10%",
    tasks:[
      { code:"I.1", title:"Behavior-Analytic Supervision Practices & Risks",
        lesson:"BCaBAs use behavior-analytic supervision — applying same principles to supervisee behavior as client behavior. Ineffective supervision creates risks including poor client outcomes and staff burnout.",
        why:"Supervision is an ABA intervention — designed, monitored, and modified using data-driven approach.",
        examples:["Behavior-analytic: modeling, feedback, reinforcement, shaping","Risks of poor supervision: unsafe implementation, poor outcomes, staff burnout","Apply: reinforce correct performance, correct errors promptly"],
        tip:"Supervise the way you would intervene with a client — with data, specific feedback, and systematic shaping.",
        mc:{q:"BCaBA provides only general positive feedback without specific behavioral feedback. Most likely result:",opts:["Strong supervisee performance","Improved supervisee morale only","Supervisee not knowing what to maintain or change","Sufficient professional development"],a:2,ex:"General praise without specific feedback doesn't teach supervisees what produced 'great.'"},
        sc:{q:"An RBT is implementing a procedure incorrectly. A behavior-analytic supervisor should:",opts:["Write formal warning","Provide immediate specific feedback, model correct procedure, observe RBT rehearse","Wait for formal supervision meeting","Email the correction"],a:1,ex:"Behavior-analytic supervision: immediate specific feedback, modeling, and rehearsal."},
        fl:{f:"Potential risks of ineffective supervision?",b:"• Poor client outcomes\n• Supervisee professional development impaired\n• Ethical violations unaddressed\n• Employee dissatisfaction and turnover\n• Organizational liability\n\nSupervision is a professional and ethical obligation"}
      },
      { code:"I.6", title:"Competency-Based Training for Supervisees",
        lesson:"BCaBAs apply empirically validated, competency-based approaches — Behavioral Skills Training (BST): instructions, modeling, rehearsal, and feedback.",
        why:"Competency-based training produces more reliable skill acquisition than didactic training alone.",
        examples:["BST: instructions, modeling, rehearsal, feedback","Train to criterion before independent implementation","Observation checklist: specific behavioral criteria for each skill"],
        tip:"Never release an RBT to implement a procedure independently until they have demonstrated competency with you present.",
        mc:{q:"BST includes all of the following EXCEPT:",opts:["Instructions","Modeling","Rehearsal","Verbal evaluation only (no direct observation)"],a:3,ex:"BST includes instructions, modeling, rehearsal, AND feedback based on direct observation."},
        sc:{q:"RBT says they understand a new procedure after watching a video. BCaBA should next:",opts:["Allow implementation — understanding is sufficient","Have RBT rehearse while BCaBA observes and provides feedback","Give written quiz","Trust RBT's self-report"],a:1,ex:"Understanding is not competency — BST requires rehearsal with observed feedback."},
        fl:{f:"4 components of BST?",b:"1. Instructions — clear description of what to do and why\n2. Modeling — supervisor demonstrates\n3. Rehearsal — supervisee practices\n4. Feedback — specific, behavioral, based on direct observation\n\nAll 4 must be present before independent implementation."}
      },
      { code:"I.8", title:"Apply a Function-Based Approach to Supervisee Behavior",
        lesson:"BCaBAs apply performance diagnostics — identifying whether supervisee problems reflect knowledge, skill, resource, or motivational deficits.",
        why:"Performance problems have environmental causes. Function-based assessment identifies solutions.",
        examples:["Knowledge deficit: training needed","Skill deficit: practice needed","Resource deficit: tools needed","Motivational deficit: reinforcement contingencies need adjustment"],
        tip:"Before assuming motivation, assess whether supervisee has knowledge, skills, materials, and reinforcement needed to perform.",
        mc:{q:"BCaBA notices RBT consistently skips a specific step. Before corrective feedback, most helpful question:",opts:["How long have they been doing this?","Does the RBT know how to do the step — knowledge or skill deficit?","How many times has this happened?","What consequences have been applied?"],a:1,ex:"Function-based: identify whether knowledge, skill, resources, or motivation before selecting intervention."},
        sc:{q:"RBT knows how to implement correctly but is inconsistent in sessions. Most likely:",opts:["Knowledge deficit","Skill deficit","Motivational or environmental issue — adjust reinforcement or conditions","Competency assessment error"],a:2,ex:"Knowledge and skill present but inconsistent = motivational or environmental issue."},
        fl:{f:"Possible reasons for supervisee performance problems?",b:"Knowledge deficit → instructions\nSkill deficit → modeling, rehearsal\nResource deficit → provide resources\nMotivational deficit → adjust reinforcement\nEnvironmental barrier → modify conditions\n\nFunction-based = identify cause BEFORE selecting solution"}
      },
    ]
  },
];
